<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
* JobRepository
*
* This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
*/
class JobRepository extends EntityRepository
{
	public function getJobs($page, $nbPerPage)
	{
		$qb = $this->createQueryBuilder('j');

		$qb->leftJoin('j.image', 'i')
		   ->addSelect('i')
		   ->leftJoin('j.categories', 'c')
		   ->addSelect('c')
		   ->orderBy('j.createdAt', 'DESC')
		   ->getQuery()
		   ;
		
		$qb
			->setFirstResult(($page-1) * $nbPerPage)
			->setMaxResults($nbPerPage)
			;

		return new Paginator($qb, true);
	}

	public function getJobsBefore(\Datetime $date)
	{
		$qb = $this->createQueryBuilder('j');

		$qb->where('j.updatedAt <= :date')                      
      	   ->orWhere('j.updatedAt IS NULL AND j.createdAt <= :date')
      	   ->andWhere('j.applications IS EMPTY')             
      	   ->setParameter('date', $date);

    	return $qb
       			 ->getQuery()
       			 ->getResult()
      			;
	}

}
