# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
    app.antispam.min_length: 50

services:

    app.antispam:
        class: AppBundle\Antispam\Antispam
        arguments:
            - '@mailer'
            - '%app.antispam.min_length%'
        calls:
            - [ setLocale, [%locale%] ]

    app.twig.antispam_extension:
        class: AppBundle\Twig\AntispamExtension
        arguments:
            - '@app.antispam'
        tags:
            -  { name: twig.extension }

    app.email.application_mailer:
        class: AppBundle\Email\ApplicationMailer
        arguments:
            - '@mailer'

    app.doctrine_listener.application_creation:
        class: AppBundle\DoctrineListener\ApplicationCreationListener
        arguments:
            - '@app.email.application_mailer'
        tags:
            - { name: doctrine.event_listener, event: postPersist }

    app.purger.job:
        class: AppBundle\Purger\JobPurger
        arguments:
            - '@doctrine.orm.entity_manager'
